[package]
name = "contender_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
contender_core = { workspace = true }
r2d2_sqlite = {workspace = true}
rusqlite = {workspace = true}
r2d2 = {workspace = true}
alloy = { workspace = true }
serde = { workspace = true }